# Generated by Django 4.2.1 on 2024-04-28 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_organizer_is_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
